// Optional live-browser tests: point a localhost server at the disposable
// directory generated by tests/fixtures/pipeline-status.mjs, then set
// LOADING_TRANSITION_TEST_URL and LOADING_TRANSITION_TEST_ROOT.
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";

const url = process.env.LOADING_TRANSITION_TEST_URL;
const root = process.env.LOADING_TRANSITION_TEST_ROOT;

test("loading transitions keep context and only latest requests settle Today", {
  skip: !url || !root,
  timeout: 120_000,
}, async (t) => {
  const origin = new URL(url);
  assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(origin.hostname));
  const relative = path.relative(os.tmpdir(), fs.realpathSync(root));
  assert.ok(relative && !relative.startsWith("..") && !path.isAbsolute(relative));
  assert.equal(fs.readFileSync(path.join(root, ".inline-status-fixture"), "utf8").trim(), "fictional-only");
  const tracker = path.join(root, "data/applications.md");
  const initial = fs.readFileSync(tracker, "utf8");
  for (const name of ["Fixture Alpha", "Fixture Beta", "Fixture Gamma"]) assert.ok(initial.includes(name));

  const { chromium } = await import("playwright-core");
  const browser = await chromium.launch({ channel: "chrome", headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const tab = (label) => page.getByRole("button", { name: new RegExp(`^${label} \\d+$`) });
  const heading = page.getByRole("heading", { level: 1 });
  const updatesAlert = page.getByRole("alert").filter({ hasText: "could not be loaded." });
  async function until(check) {
    const started = Date.now();
    while (!await check()) {
      if (Date.now() - started > 15_000) assert.fail("UI did not reach expected state");
      await page.waitForTimeout(50);
    }
  }
  function gate() {
    let release;
    const promise = new Promise((resolve) => { release = resolve; });
    return { promise, release };
  }

  // Put every fictional row beyond the awaiting-decision queue so a false
  // all-clear is observable; writes still use the canonical status API.
  // Check the server, not just the local marker: a misconfigured test URL
  // must never direct fixture mutations at a personal tracker.
  await page.goto(`${origin.origin}/pipeline?tab=ALL`);
  await page.getByRole("button", { name: /^Edit status/ }).first().waitFor();
  assert.equal(await page.locator("tbody tr").count(), 3);
  for (const [n, company] of [["11", "Fixture Alpha"], ["12", "Fixture Beta"], ["13", "Fixture Gamma"]]) {
    const row = page.locator("tbody tr").filter({ has: page.getByRole("link", { name: `#${n}`, exact: true }) });
    assert.ok((await row.innerText()).includes(company));
  }
  for (const n of ["11", "12", "13"]) {
    const response = await page.request.post(`${origin.origin}/api/status`, { data: { n, status: "Applied" } });
    assert.equal(response.status(), 200);
  }
  const baseline = fs.readFileSync(tracker, "utf8");

  await t.test("Pipeline filter keeps heading, search, tabs and result skeletons", async (subtest) => {
    await page.goto(`${origin.origin}/pipeline?tab=ALL`);
    await page.getByRole("button", { name: /^Edit status/ }).first().waitFor();
    const pending = gate();
    let held = false;
    subtest.after(async () => { pending.release(); await page.unrouteAll({ behavior: "wait" }); });
    await page.route("**/pipeline?**", async (route) => {
      if (route.request().headers().rsc === "1") { held = true; await pending.promise; }
      await route.continue();
    });
    await tab("APPLIED").click();
    await until(() => held);
    assert.equal(await heading.innerText(), "Pipeline");
    assert.equal(await page.getByPlaceholder("Search company or role…").isVisible(), true);
    assert.equal(await tab("ALL").isVisible(), true);
    assert.equal(await page.locator('tbody[aria-busy="true"]').count(), 1);
    assert.ok(await page.locator('tbody[aria-busy="true"] tr').count() > 0);
    assert.equal(await page.locator('tbody[aria-busy="true"] tr').first().locator("td").count(), await page.locator("thead th").count());
    pending.release();
    await page.waitForURL(/tab=APPLIED/);
    await page.locator('tbody[aria-busy="false"]').waitFor();
    assert.equal(await page.getByRole("button", { name: /^Edit status/ }).count(), 3);
  });

  await t.test("Follow-ups query transition retains page context", async (subtest) => {
    await page.goto(`${origin.origin}/followups`);
    await page.locator("tbody tr").first().waitFor();
    const pending = gate();
    let held = false;
    subtest.after(async () => { pending.release(); await page.unrouteAll({ behavior: "wait" }); });
    await page.route("**/followups?**", async (route) => {
      if (route.request().headers().rsc === "1") { held = true; await pending.promise; }
      await route.continue();
    });
    await page.getByRole("button", { name: /^Company/ }).click();
    await until(() => held);
    assert.equal(await heading.innerText(), "Follow-up Tracker");
    assert.equal(await page.getByPlaceholder("Search company or role…").isVisible(), true);
    assert.equal(await tab("ALL").isVisible(), true);
    assert.equal(await page.locator('tbody[aria-busy="true"]').count(), 1);
    assert.ok(await page.locator('tbody[aria-busy="true"] tr').count() > 0);
    pending.release();
    await page.waitForURL(/sort=company/);
    await page.locator('tbody[aria-busy="false"]').waitFor();
  });

  const emptyFollowups = { available: true, entries: [], metadata: { overdue: 0, urgent: 0 }, nextUpcoming: null };
  const emptyFresh = { offers: [], count: 0 };
  await t.test("failed fetch never says all-clear and Retry restarts loading", async (subtest) => {
    const pending = gate();
    let retry = false;
    const seen = new Set();
    subtest.after(async () => { pending.release(); await page.unrouteAll({ behavior: "wait" }); });
    await page.route(/\/api\/(followups|whats-new)(\?|$)/, async (route) => {
      const endpoint = new URL(route.request().url()).pathname;
      seen.add(endpoint);
      if (!retry) return route.fulfill({ status: 503, json: { error: "Fixture unavailable" } });
      await pending.promise;
      await route.fulfill({ json: endpoint === "/api/followups" ? emptyFollowups : emptyFresh });
    });
    await page.goto(origin.origin);
    await page.getByRole("button", { name: "Retry updates" }).waitFor();
    assert.equal(await heading.innerText(), "Some updates are unavailable.");
    assert.equal(await updatesAlert.isVisible(), true);
    assert.equal(await page.getByText("You're all caught up.", { exact: true }).count(), 0);
    retry = true;
    seen.clear();
    await page.getByRole("button", { name: "Retry updates" }).click();
    await until(() => seen.size === 2);
    assert.equal(await heading.innerText(), "Your career queue is loading.");
    await page.getByRole("region", { name: "Loading follow-ups due" }).waitFor();
    pending.release();
    await page.getByRole("heading", { name: "You're all caught up." }).waitFor();
    assert.equal(await updatesAlert.count(), 0);
  });

  await t.test("HTTP 200 cadence-unavailable is an error, not an empty queue", async (subtest) => {
    subtest.after(() => page.unrouteAll({ behavior: "wait" }));
    await page.route(/\/api\/(followups|whats-new)(\?|$)/, (route) => route.fulfill({ json:
      new URL(route.request().url()).pathname === "/api/followups"
        ? { available: false, metadata: null, entries: [], nextUpcoming: null }
        : emptyFresh,
    }));
    await page.goto(origin.origin);
    await page.getByRole("button", { name: "Retry updates" }).waitFor();
    assert.equal(await heading.innerText(), "Some updates are unavailable.");
    assert.match(await updatesAlert.innerText(), /Follow-ups could not be loaded/);
    assert.equal(await page.getByText("You're all caught up.", { exact: true }).count(), 0);
  });

  await t.test("older success cannot end a newer load; older failure cannot replace newer success", async (subtest) => {
    const gates = new Map();
    const counts = new Map();
    let completed = 0;
    subtest.after(async () => { for (const pending of gates.values()) pending.release(); await page.unrouteAll({ behavior: "wait" }); });
    await page.route(/\/api\/(followups|whats-new)(\?|$)/, async (route) => {
      const endpoint = new URL(route.request().url()).pathname;
      const index = (counts.get(endpoint) ?? 0) + 1;
      counts.set(endpoint, index);
      const pending = gate();
      gates.set(`${index}:${endpoint}`, pending);
      await pending.promise;
      if (index === 4) await route.fulfill({ status: 503, json: { error: "Old fixture request failed" } });
      else await route.fulfill({ json: index === 2
        ? endpoint === "/api/followups" ? { ...emptyFollowups, metadata: { overdue: 9, urgent: 0 } } : { offers: [], count: 99 }
        : endpoint === "/api/followups" ? emptyFollowups : emptyFresh });
      completed += 1;
    });
    const started = (index) => until(() => ["/api/followups", "/api/whats-new"].every((endpoint) => gates.has(`${index}:${endpoint}`)));
    const release = (index) => { for (const endpoint of ["/api/followups", "/api/whats-new"]) gates.get(`${index}:${endpoint}`).release(); };
    const refetch = () => page.evaluate(() => window.dispatchEvent(new Event("co-job-done")));
    await page.reload();
    await started(1);
    release(1);
    await page.getByRole("heading", { name: "You're all caught up." }).waitFor();
    await refetch(); await started(2);
    await refetch(); await started(3);
    release(2);
    await until(() => completed === 4);
    await page.waitForTimeout(100);
    assert.equal(await heading.innerText(), "Your career queue is loading.");
    gates.get("3:/api/whats-new").release();
    await until(() => completed === 5);
    assert.equal(await heading.innerText(), "Your career queue is loading.");
    gates.get("3:/api/followups").release();
    await page.getByRole("heading", { name: "You're all caught up." }).waitFor();
    await refetch(); await started(4);
    await refetch(); await started(5);
    release(5);
    await page.getByRole("heading", { name: "You're all caught up." }).waitFor();
    release(4);
    await until(() => completed === 10);
    await page.waitForTimeout(100);
    assert.equal(await heading.innerText(), "You're all caught up.");
    assert.equal(await updatesAlert.count(), 0);
  });

  assert.equal(fs.readFileSync(tracker, "utf8"), baseline, "loading/filter/retry interactions never write user data");
  assert.deepEqual(errors, []);
});
